/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelobeans.Modalidade;
import Modelobeans.ModeloTable;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import modeloConection.ConexaoBD;
import modeloDao.ContModalidade;

/**
 *
 * @author Tsandzana
 */
public class InternalModlist extends javax.swing.JInternalFrame {
ConexaoBD conex=new ConexaoBD();
Modalidade mod=new Modalidade();
ContModalidade ms=new ContModalidade();

    /**
     * Creates new form InternalModlist
     */
    public InternalModlist() {
        initComponents();
         setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
         preencherTabela("Select *from Modalidade order by codigoM");
         this.designerTa();
         
    }

    private void designerTa(){
        tbdados.getTableHeader().setFont(new Font("segoe UI", Font.BOLD, 12));
        tbdados.getTableHeader().setOpaque(false);
        tbdados.getTableHeader().setBackground(new Color(51,51,51));
        tbdados.getTableHeader().setForeground(new Color(255,255,255));
        tbdados.setRowHeight(25);
    }
    
    public void preencherTabela(String sql){
        ArrayList dados=new ArrayList();
       String[] colunas=new String[]{"Codigo","Modalidade","Escalao"};
       conex.Conexao();
       conex.executeSql(sql);
       try{
           conex.rs.first();
           do{
               dados.add(new Object[]{conex.rs.getInt("CodigoM"),conex.rs.getString("nome"),conex.rs.getInt("EscalaoID")});
           }while(conex.rs.next());
       }catch(SQLException ex){
          // JOptionPane.showMessageDialog(rootPane,"erro ao preencher arraylist"+ex.getMessage());
       }
       ModeloTable modelo=new ModeloTable(dados,colunas);
       tbdados.setModel(modelo);
       tbdados.getColumnModel().getColumn(0).setPreferredWidth(280);
       tbdados.getColumnModel().getColumn(0).setResizable(false);
       tbdados.getColumnModel().getColumn(1).setPreferredWidth(420);
       tbdados.getColumnModel().getColumn(1).setResizable(false);
       tbdados.getColumnModel().getColumn(2).setPreferredWidth(395);
       tbdados.getColumnModel().getColumn(2).setResizable(false);
       tbdados.getTableHeader().setReorderingAllowed(false);
       tbdados.setAutoResizeMode(tbdados.AUTO_RESIZE_OFF);
       tbdados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       conex.Desconectar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dep = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btcancelar = new javax.swing.JButton();
        bteditar = new javax.swing.JButton();
        btremover = new javax.swing.JButton();
        btvisualizar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdados = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        btcancelar.setBackground(new java.awt.Color(204, 204, 204));
        btcancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.setBorder(null);
        btcancelar.setEnabled(false);
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        bteditar.setBackground(new java.awt.Color(204, 204, 204));
        bteditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bteditar.setText("Editar");
        bteditar.setBorder(null);
        bteditar.setEnabled(false);
        bteditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditarActionPerformed(evt);
            }
        });

        btremover.setBackground(new java.awt.Color(204, 204, 204));
        btremover.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btremover.setText("Remover");
        btremover.setBorder(null);
        btremover.setEnabled(false);
        btremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btremoverActionPerformed(evt);
            }
        });

        btvisualizar.setBackground(new java.awt.Color(204, 204, 204));
        btvisualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btvisualizar.setText("Visaulizar");
        btvisualizar.setBorder(null);
        btvisualizar.setEnabled(false);
        btvisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvisualizarActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Pesquisar");

        tbdados.setBackground(new java.awt.Color(255, 255, 255));
        tbdados.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbdados.setForeground(new java.awt.Color(0, 0, 0));
        tbdados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbdados.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbdados.setRowHeight(25);
        tbdados.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tbdados.setShowVerticalLines(false);
        tbdados.getTableHeader().setReorderingAllowed(false);
        tbdados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(569, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btvisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btremover, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bteditar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btremover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btvisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bteditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        dep.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout depLayout = new javax.swing.GroupLayout(dep);
        dep.setLayout(depLayout);
        depLayout.setHorizontalGroup(
            depLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        depLayout.setVerticalGroup(
            depLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dep)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bteditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditarActionPerformed
        String nome=""+tbdados.getValueAt(tbdados.getSelectedRow(),1);
        conex.Conexao();
        conex.executeSql("select *from Modalidade where nome='"+nome+"'");
        InternalModalidade rt=new InternalModalidade();
        dep.add(rt);
        rt.show();
        try{
            conex.rs.first();
            rt.getcod().setText(String.valueOf(conex.rs.getInt("CodigoM")));
            rt.getmo().setText(conex.rs.getString("Nome"));
            conex.executeSql("Select nome From escalao where codigoE=" + conex.rs.getInt("EscalaoID") + "");
        conex.rs.first();
        rt.getesc().setSelectedItem(conex.rs.getString("Nome"));
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"erro ao selecionar os dados\n"+ex.getMessage());
        }
         rt.getbtnovo().setEnabled(false);
        rt.getgravar().setEnabled(true);
        rt.getcancelar().setEnabled(true);
        rt.getmo().setEnabled(true);
        rt.getesc().setEnabled(true);
    }//GEN-LAST:event_bteditarActionPerformed

    private void btremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btremoverActionPerformed
        int resposta=0;
        String nom=""+tbdados.getValueAt(tbdados.getSelectedRow(),1);
        resposta=JOptionPane.showConfirmDialog(rootPane,"Deseja realmente remover esse dado?");
        if(resposta==JOptionPane.YES_OPTION){
            mod.setNome(nom);
            ms.remover(mod);
            preencherTabela("Select *from Modalidade order by codigoM");
        }
        btcancelar.setEnabled(true);
        bteditar.setEnabled(true);
        btremover.setEnabled(true);
        btvisualizar.setEnabled(true);
    }//GEN-LAST:event_btremoverActionPerformed

    private void btvisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvisualizarActionPerformed
        telaMod m=new telaMod();
        m.setVisible(true);
        String nome=""+tbdados.getValueAt(tbdados.getSelectedRow(),1);
        conex.Conexao();
        conex.executeSql("select *from Modalidade where nome='"+nome+"'");
        try{
            conex.rs.first();
            m.gett().setText(String.valueOf(conex.rs.getInt("codigoM")));
            m.getnome().setText(conex.rs.getString("Nome"));
            m.getesca().setText(String.valueOf(conex.rs.getString("escalaoID")));

        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"erro ao selecionar os dados\n"+ex.getMessage());
        }
         btcancelar.setEnabled(false);
        bteditar.setEnabled(false);
        btremover.setEnabled(false);
        btvisualizar.setEnabled(false);
          preencherTabela("Select *from Modalidade order by codigoM");
    }//GEN-LAST:event_btvisualizarActionPerformed

    private void tbdadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdadosMouseClicked
        btcancelar.setEnabled(true);
        bteditar.setEnabled(true);
        btremover.setEnabled(true);
        btvisualizar.setEnabled(true);
    }//GEN-LAST:event_tbdadosMouseClicked

    public JButton getbteditar(){
     return bteditar;
 }
 public JButton getremov(){
     return  btremover;
 }
 
 public JButton getvisu(){
     return  btvisualizar;
 } 
 
 public JButton getcancelar(){
     return btcancelar;
 }
    
    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
      btcancelar.setEnabled(false);
        bteditar.setEnabled(false);
        btremover.setEnabled(false);
        btvisualizar.setEnabled(false);
        preencherTabela("Select *from Modalidade order by codigoM");
    }//GEN-LAST:event_btcancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton bteditar;
    private javax.swing.JButton btremover;
    private javax.swing.JButton btvisualizar;
    private javax.swing.JDesktopPane dep;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbdados;
    // End of variables declaration//GEN-END:variables
}
