/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelobeans.ModeloTable;
import Modelobeans.beans_treinador;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import modeloConection.ConexaoBD;
import modeloDao.ContTreinador;

/**
 *
 * @author Evandro
 */
public class InternalistTreinador extends javax.swing.JInternalFrame {
ConexaoBD conex=new ConexaoBD();
ContTreinador tr=new ContTreinador();
beans_treinador mo=new beans_treinador();
InternalTreinador it=new InternalTreinador();
    /**
     * Creates new form InternalistTreinador
     */
    public InternalistTreinador() {
        initComponents(); setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        PreencherTable("select *from treinador order by codigoT");
        designerTa();
    }
    private void designerTa(){
        tbdados.getTableHeader().setFont(new Font("segoe UI", Font.BOLD, 12));
        tbdados.getTableHeader().setOpaque(false);
        tbdados.getTableHeader().setBackground(new Color(51,51,51));
        tbdados.getTableHeader().setForeground(new Color(255,255,255));
        tbdados.setRowHeight(25);
    }
     private void PreencherTable(String sql){
        ArrayList dados=new ArrayList();
        String[] colunas=new String[]{"Codigo","Nome","Sexo","Data de Nascimento","Morada","Contacto","Nr de documento","Escalao","Modalidade"};
        conex.Conexao();
        conex.executeSql(sql);
        try{
           conex.rs.first();   
        do{
            dados.add(new Object[]{conex.rs.getInt("CodigoT"),conex.rs.getString("nome"),conex.rs.getString("sexo"),conex.rs.getString("data"),conex.rs.getString("morada"),conex.rs.getInt("contacto"),conex.rs.getString("nrdoc"),conex.rs.getInt("escalao"),conex.rs.getInt("modalidade")});
           }while(conex.rs.next());
    }catch(SQLException ex){
      // JOptionPane.showMessageDialog(rootPane,"erro ao preencher a table\n:"+ex.getMessage());
    }
         ModeloTable modelo=new ModeloTable(dados,colunas);
       tbdados.setModel(modelo);
       tbdados.getColumnModel().getColumn(0).setPreferredWidth(100);
       tbdados.getColumnModel().getColumn(0).setResizable(false);
        tbdados.getColumnModel().getColumn(1).setPreferredWidth(200);
       tbdados.getColumnModel().getColumn(1).setResizable(false);
        tbdados.getColumnModel().getColumn(2).setPreferredWidth(110);
       tbdados.getColumnModel().getColumn(2).setResizable(false);
        tbdados.getColumnModel().getColumn(3).setPreferredWidth(130);
       tbdados.getColumnModel().getColumn(3).setResizable(false);
        tbdados.getColumnModel().getColumn(4).setPreferredWidth(150);
       tbdados.getColumnModel().getColumn(4).setResizable(false);
        tbdados.getColumnModel().getColumn(5).setPreferredWidth(110);
       tbdados.getColumnModel().getColumn(5).setResizable(false);
       tbdados.getColumnModel().getColumn(6).setPreferredWidth(110);
       tbdados.getColumnModel().getColumn(6).setResizable(false);
       tbdados.getColumnModel().getColumn(7).setPreferredWidth(90);
       tbdados.getColumnModel().getColumn(7).setResizable(false);
       tbdados.getColumnModel().getColumn(8).setPreferredWidth(100);
       tbdados.getColumnModel().getColumn(8).setResizable(false);
       tbdados.getTableHeader().setReorderingAllowed(false);
       tbdados.setAutoResizeMode(tbdados.AUTO_RESIZE_OFF);
       tbdados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       conex.Desconectar();
    }
     
      class JPanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
           Graphics2D g2d=(Graphics2D) g;
           int width=getWidth();
           int Height=getHeight();
           
           Color color1=new Color(51,51,51);
           Color color2=new Color(187,187,187);
           GradientPaint gp=new GradientPaint(0,0,color1,180,Height,color2);
           g2d.setPaint(gp);
           g2d.fillRect(0,0, width, Height);
    }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desw = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdados = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        bteditar = new javax.swing.JButton();
        btremover = new javax.swing.JButton();
        btvisualizar = new javax.swing.JButton();

        desw.setBackground(new java.awt.Color(102, 102, 102));

        tbdados.setBackground(new java.awt.Color(255, 255, 255));
        tbdados.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbdados.setForeground(new java.awt.Color(0, 0, 0));
        tbdados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbdados.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbdados.setRowHeight(25);
        tbdados.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tbdados.setShowVerticalLines(false);
        tbdados.getTableHeader().setReorderingAllowed(false);
        tbdados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdados);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Pesquisar");

        btcancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btcancelar.setForeground(new java.awt.Color(0, 0, 0));
        btcancelar.setText("Cancelar");
        btcancelar.setEnabled(false);
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        bteditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bteditar.setForeground(new java.awt.Color(0, 0, 0));
        bteditar.setText("Editar");
        bteditar.setEnabled(false);
        bteditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditarActionPerformed(evt);
            }
        });

        btremover.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btremover.setForeground(new java.awt.Color(0, 0, 0));
        btremover.setText("Remover");
        btremover.setEnabled(false);
        btremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btremoverActionPerformed(evt);
            }
        });

        btvisualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btvisualizar.setForeground(new java.awt.Color(0, 0, 0));
        btvisualizar.setText("Visualizar");
        btvisualizar.setEnabled(false);

        desw.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desw.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desw.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desw.setLayer(btcancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desw.setLayer(bteditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desw.setLayer(btremover, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desw.setLayer(btvisualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deswLayout = new javax.swing.GroupLayout(desw);
        desw.setLayout(deswLayout);
        deswLayout.setHorizontalGroup(
            deswLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deswLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deswLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deswLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deswLayout.createSequentialGroup()
                        .addComponent(btvisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btremover, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bteditar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deswLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        deswLayout.setVerticalGroup(
            deswLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deswLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deswLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deswLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deswLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btcancelar)
                        .addComponent(bteditar)
                        .addComponent(btremover))
                    .addComponent(btvisualizar))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desw, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desw)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbdadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdadosMouseClicked
      btvisualizar.setEnabled(true);
      btcancelar.setEnabled(true);
      btremover.setEnabled(true);
      bteditar.setEnabled(true);
    }//GEN-LAST:event_tbdadosMouseClicked

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
       btvisualizar.setEnabled(false);
      btcancelar.setEnabled(false);
      btremover.setEnabled(false);
      bteditar.setEnabled(false);
       PreencherTable("select *from treinador order by codigoT");
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btremoverActionPerformed
      int resposta=0;
   String nome=""+tbdados.getValueAt(tbdados.getSelectedRow(),1);
    resposta=JOptionPane.showConfirmDialog(rootPane,"Deseja realmente remover esse dado?");
    if(resposta==JOptionPane.YES_OPTION){
     mo.setNome(nome);
     tr.remover(mo);
      PreencherTable("select *from treinador order by codigoT");
       btvisualizar.setEnabled(false);
      btcancelar.setEnabled(false);
      btremover.setEnabled(false);
      bteditar.setEnabled(false);
    }
    }//GEN-LAST:event_btremoverActionPerformed

    private void bteditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditarActionPerformed
      String nome=""+tbdados.getValueAt(tbdados.getSelectedRow(),1);
   conex.Conexao();
    conex.executeSql("select *from treinador where nome='"+nome+"'");
    InternalTreinador rt=new InternalTreinador();    
    desw.add(rt);
    rt.show();
    try{
        conex.rs.first();
        rt.getcod().setText(String.valueOf(conex.rs.getInt("CodigoT")));
          rt.nome().setText(conex.rs.getString("Nome"));
            String q=conex.rs.getString("sexo");
         if(q.equalsIgnoreCase("masculino")){
           rt.masc().setSelected(true);
             rt.fem().setSelected(false);
        }else{
             rt.fem().setSelected(true);
             rt.masc().setSelected(false);
        }
          rt.num().setText(conex.rs.getString("nrdoc"));
           rt.esc().setSelectedItem(conex.rs.getString("Nome"));
         rt.data().setText(conex.rs.getString("data"));
         rt.mo().setText(conex.rs.getString("morada"));
         rt.cont().setText(String.valueOf(conex.rs.getInt("contacto")));
          int e,b;
                e=conex.rs.getInt("Escalao") ;
                b=conex.rs.getInt("modalidade");
           conex.executeSql("Select nome From modalidade where codigoM=" + b+ "");
        conex.rs.first();
        rt.mod().setSelectedItem(conex.rs.getString("Nome"));
         conex.executeSql("Select nome From escalao where codigoE=" + e+ "");
        conex.rs.first();
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"erro ao selecionar os dados\n"+ex.getMessage());
    }
    rt.novo().setEnabled(false);
    rt.gravar().setEnabled(true);
    rt.cancela().setEnabled(true);
    rt.getcod().setEnabled(true);
    rt.nome().setEnabled(true);
    rt.data().setEnabled(true);
    rt.mo().setEnabled(true);
    rt.fem().setEnabled(true);
    rt.masc().setEnabled(true);
    rt.cont().setEnabled(true);
    rt.num().setEnabled(true);
    rt.esc().setEnabled(true);
    rt.mod().setEnabled(true);
    }//GEN-LAST:event_bteditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton bteditar;
    private javax.swing.JButton btremover;
    private javax.swing.JButton btvisualizar;
    private javax.swing.JDesktopPane desw;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbdados;
    // End of variables declaration//GEN-END:variables
}
