/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelobeans.*;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import modeloConection.ConexaoBD;
import modeloDao.Contcalendario;

/**
 *
 * @author Evandro
 */
public class InternalCalendario extends javax.swing.JInternalFrame {
 byte flag=0;
 ConexaoBD conex=new ConexaoBD();
 ModCalendario cal=new ModCalendario();
 Contcalendario cont=new Contcalendario();
    /**
     * Creates new form InternalCalendario
     */
    public InternalCalendario() {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        this.carregaEscalao();
        this.carregaModalidade();
    }
    
        class JPanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
           Graphics2D g2d=(Graphics2D) g;
           int width=getWidth();
           int Height=getHeight();
           
           Color color1=new Color(187,187,187);
           Color color2=new Color(51,51,51);
           GradientPaint gp=new GradientPaint(0,0,color1,180,Height,color2);
           g2d.setPaint(gp);
           g2d.fillRect(0,0, width, Height);
    }
    }

    public JTextField getJornada(){
        return txtjornada;
    }
    public JTextField getJogo(){
        return txtjogo;
    }
    public JTextField getData(){
        return txtdata;
    }
    public JTextField getCampo(){
        return txtcampo;
    }
    public JComboBox getMod(){
        return cbmod;
    }
    public JComboBox getEsc(){
        return cbesc;
    }
    public JButton getNovo(){
        return btnovo;
    }
    public JButton getGravar(){
        return btgravar;
    }
    public JButton getCancelar(){
        return btcancelar;
    }
    
    public int verificarMod(String dado){
        conex.Conexao();
        ResultSet rs=cont.Modalidade();
        int id=0;
        try{
            rs.beforeFirst();
            while(rs.next()){
                if(rs.getString("nome").equalsIgnoreCase(dado)){
                    id=rs.getInt("codigoM");
                    break;
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Erro na verificacao do dado\n"+ex.getMessage());
        }
        return id;
    }
    
    public int VerificarEsc(String dado){
        conex.Conexao();
        ResultSet rs=cont.escalao();
        int id=0;
        try{
            rs.beforeFirst();
            while(rs.next()){
                if(rs.getString("nome").equalsIgnoreCase(dado)){
                    id=rs.getInt("CodigoE");
                    break;
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Erro na verificacao do dado\n"+ex.getMessage());
        }
        return id;
    }
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtjornada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtjogo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcampo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdata = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbmod = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbesc = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new JPanelGradient();
        btnovo = new javax.swing.JButton();
        btgravar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Jornada");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 109, 30));

        txtjornada.setBackground(new java.awt.Color(204, 204, 204));
        txtjornada.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtjornada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtjornada.setEnabled(false);
        jPanel2.add(txtjornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 125, 230, 28));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Jogo");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 148, 30));

        txtjogo.setBackground(new java.awt.Color(204, 204, 204));
        txtjogo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtjogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtjogo.setEnabled(false);
        jPanel2.add(txtjogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 125, 300, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Campo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 210, 20));

        txtcampo.setBackground(new java.awt.Color(204, 204, 204));
        txtcampo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcampo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtcampo.setEnabled(false);
        jPanel2.add(txtcampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 229, 230, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Data/Horario o Jogo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 233, 20));

        txtdata.setBackground(new java.awt.Color(204, 204, 204));
        txtdata.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtdata.setEnabled(false);
        jPanel2.add(txtdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 229, 300, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Modalidade");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 281, 27));

        cbmod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbmod.setForeground(new java.awt.Color(0, 0, 0));
        cbmod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbmod.setEnabled(false);
        cbmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmodActionPerformed(evt);
            }
        });
        jPanel2.add(cbmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 230, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Escalao");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 210, 27));

        cbesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbesc.setForeground(new java.awt.Color(0, 0, 0));
        cbesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbesc.setEnabled(false);
        cbesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbescActionPerformed(evt);
            }
        });
        jPanel2.add(cbesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 300, 29));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 230, 4));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 290, 4));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 230, 1));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 310, 1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 840, 450));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Table Tennis_48px.png"))); // NOI18N
        jLabel7.setText("Sport Gerentior");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Registro do Calendario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307)
                .addComponent(jLabel8)
                .addGap(0, 445, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1147, -1));

        btnovo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnovo.setText("Novo");
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        btgravar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btgravar.setText("Gravar");
        btgravar.setEnabled(false);
        btgravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgravarActionPerformed(evt);
            }
        });

        btcancelar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.setEnabled(false);
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btgravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(btnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btgravar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
      flag=1;
      txtcampo.setEnabled(true);
      txtdata.setEnabled(true);
      txtjogo.setEnabled(true);
      txtjornada.setEnabled(true);
      cbesc.setEnabled(true);
      cbmod.setEnabled(true);
      btgravar.setEnabled(true);
      btcancelar.setEnabled(true);
      btnovo.setEnabled(false);
    }//GEN-LAST:event_btnovoActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
      txtcampo.setEnabled(false);
      txtdata.setEnabled(false);
      txtjogo.setEnabled(false);
      txtjornada.setEnabled(false);
      cbesc.setEnabled(false);
      cbmod.setEnabled(false);
      btgravar.setEnabled(false);
      btcancelar.setEnabled(false);
      btnovo.setEnabled(true);
      txtcampo.setText("");
      txtdata.setText("");
      txtjogo.setText("");
      txtjornada.setText("");
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btgravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgravarActionPerformed
      if(txtjornada.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Campo Jornada Vazio");
          txtjornada.requestFocus();
      }else
          if(txtjogo.getText().isEmpty()){
              JOptionPane.showMessageDialog(null,"campo jogo Vazio");
              txtjogo.requestFocus();
          }else
              if(txtdata.getText().isEmpty()){
                  JOptionPane.showMessageDialog(null,"Campo Data vazio");
                  txtdata.requestFocus();
              }else
                  if(txtcampo.getText().isEmpty()){
                      JOptionPane.showMessageDialog(null,"Campo vazio");
                      txtcampo.requestFocus();
                  }else
                      if(flag==1){
                          cal.setJornada(txtjornada.getText());
                          cal.setJogo(txtjogo.getText());
                          cal.setDatahorario(txtdata.getText());
                          cal.setCampo(txtcampo.getText());
                          cal.setModalidade(verificarMod((String)cbmod.getSelectedItem()));
                          cal.setEscalao(VerificarEsc((String)cbesc.getSelectedItem()));
                          cont.gravar(cal);
                           btnovo.setEnabled(true);
                          txtcampo.setText("");
                          txtdata.setText("");
                          txtjogo.setText("");
                           txtjornada.setText("");
                          btcancelar.setEnabled(false);
                          btgravar.setEnabled(false);
                      }else{
                          cal.setJornada(txtjornada.getText());
                          cal.setJogo(txtjogo.getText());
                          cal.setDatahorario(txtdata.getText());
                          cal.setCampo(txtcampo.getText());
                          cal.setModalidade(verificarMod((String)cbmod.getSelectedItem()));
                          cal.setEscalao(VerificarEsc((String)cbesc.getSelectedItem()));
                          cont.editar(cal);
                          btnovo.setEnabled(true);
                          txtcampo.setText("");
                          txtdata.setText("");
                          txtjogo.setText("");
                           txtjornada.setText("");
                          btcancelar.setEnabled(false);
                          btgravar.setEnabled(false);
                      }
    }//GEN-LAST:event_btgravarActionPerformed

    private void cbmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmodActionPerformed
        try{
            ResultSet rs=cont.ModalidadeBaynome(cbmod.getSelectedItem().toString());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Erro ao preencher combo box");
        }
    }//GEN-LAST:event_cbmodActionPerformed

    private void cbescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbescActionPerformed
        try{
            ResultSet rs=cont.escalaoBaynome(cbesc.getSelectedItem().toString());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Erro ao preencher a combo box\n"+ex.getMessage());
        }
    }//GEN-LAST:event_cbescActionPerformed

   public void carregaModalidade(){
       try{
           ResultSet rs=cont.Modalidade();
           rs.beforeFirst();
           while(rs.next()){
               Modalidade mod=new Modalidade();
               mod.setCodigo(rs.getInt("CodigoM"));
               mod.setNome(rs.getString("nome"));
               try{
                   cbmod.addItem((String)(Object)(mod.getNome()));
               }catch(NullPointerException e){
                   
               }
           }
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null,"Erro ao carregar dados");
       }
   }
   public void carregaEscalao(){
       try{
           ResultSet rs=cont.escalao();
           rs.beforeFirst();
           while(rs.next()){
               ModEscalao esc=new ModEscalao();
               esc.setCodigo(rs.getInt("CodigoE"));
               esc.setNome(rs.getString("nome"));
               try{
                   cbesc.addItem((String)(Object)(esc.getNome()));
               }catch(NullPointerException e){
                   
               }
           }
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null,"Erro ao carregar os dados\n"+ex.getMessage());
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btgravar;
    private javax.swing.JButton btnovo;
    private javax.swing.JComboBox<String> cbesc;
    private javax.swing.JComboBox<String> cbmod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtcampo;
    private javax.swing.JTextField txtdata;
    private javax.swing.JTextField txtjogo;
    private javax.swing.JTextField txtjornada;
    // End of variables declaration//GEN-END:variables
}
