/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelobeans.Ficha;
import Modelobeans.ModEscalao;
import Modelobeans.Modalidade;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import modeloConection.ConexaoBD;
import modeloDao.ContFicha;

/**
 *
 * @author Evandro
 */
public class InternalFicha extends javax.swing.JInternalFrame {
ConexaoBD conex=new ConexaoBD();
Ficha fic=new Ficha();
ContFicha cf=new ContFicha();
Modalidade mods=new Modalidade();
ModEscalao esca=new ModEscalao();
int flag=0;
    /**
     * Creates new form InternalFicha
     */
    public InternalFicha() {
        initComponents();
         setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        this.carregarEscalao();
        this.carregarmodalidade();
    }
    
    class JPanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
           Graphics2D g2d=(Graphics2D) g;
           int width=getWidth();
           int Height=getHeight();
           
           Color color1=new Color(187,187,187);
           Color color2=new Color(51,51,51);
           GradientPaint gp=new GradientPaint(0,0,color1,180,Height,color2);
           g2d.setPaint(gp);
           g2d.fillRect(0,0, width, Height);
    }
    }
    
    public JTextField cod(){
        return txtcod;
    }
    
     public JTextField nome(){
        return txtnome;
    }
      public JTextField cartA(){
        return txtcartaoA;
    }
       public JTextField cartV(){
        return txtcartaoV;
    }
        public JTextField golM(){
        return txtgoM;
    }
         public JTextField golS(){
        return txtgos;
    }
          public JTextField ano(){
        return txtano;
    }
           public JTextField num(){
        return txtnum;
    }
            public JTextField nump(){
        return txtnump;
    }
             public JTextField pos(){
        return txtpos;
    }
             public JComboBox esc(){
                 return cbesc;
             }
             public JComboBox mod(){
                 return cbmod;
             }
             public JButton novo(){
                 return novo;
             }
              public JButton grava(){
                 return grava;
             }
               public JButton cancela(){
                 return  cancela;
             }
    
     private int verifica(String dado){
     conex.Conexao();
        ResultSet rs = cf.escalao();
           int id=0;
           try{
           rs.beforeFirst();
           while(rs.next()){
               if(rs.getString("nome").equalsIgnoreCase(dado)){
                   id=rs.getInt("codigoE");
                   break;
               }
           }
           }catch(SQLException se){
               JOptionPane.showMessageDialog(null,se.getMessage());
           }
           return id;
    }
 private int verificas(String dado){
        ResultSet rs = cf.Modalidade();
           int id=0;
           try{
           rs.beforeFirst();
           while(rs.next()){
               if(rs.getString("nome").equalsIgnoreCase(dado)){
                   id=rs.getInt("codigoM");
                   break;
               }
           }
           }catch(SQLException se){
               JOptionPane.showMessageDialog(null,se.getMessage());
           }
           return id;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbesc = new javax.swing.JComboBox<>();
        cbmod = new javax.swing.JComboBox<>();
        txtpos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtgoM = new javax.swing.JTextField();
        txtgos = new javax.swing.JTextField();
        txtnump = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtcartaoA = new javax.swing.JTextField();
        txtcartaoV = new javax.swing.JTextField();
        txtano = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new JPanelGradient();
        novo = new javax.swing.JButton();
        grava = new javax.swing.JButton();
        cancela = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jDesktopPane1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Codigo do Atleta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 23));

        txtcod.setBackground(new java.awt.Color(204, 204, 204));
        txtcod.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcod.setForeground(new java.awt.Color(0, 0, 0));
        txtcod.setBorder(null);
        txtcod.setEnabled(false);
        jPanel1.add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 165, 29));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 172, -1));

        txtnome.setBackground(new java.awt.Color(204, 204, 204));
        txtnome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtnome.setForeground(new java.awt.Color(0, 0, 0));
        txtnome.setBorder(null);
        txtnome.setEnabled(false);
        jPanel1.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 51, 250, 29));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Numero de Jogos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 129, 23));

        txtnum.setBackground(new java.awt.Color(204, 204, 204));
        txtnum.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtnum.setForeground(new java.awt.Color(0, 0, 0));
        txtnum.setBorder(null);
        txtnum.setEnabled(false);
        jPanel1.add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 51, 173, 29));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Escalao");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 165, 25));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Modalidade");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 144, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Posicao");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 130, 20));

        cbesc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbesc.setForeground(new java.awt.Color(0, 0, 0));
        cbesc.setEnabled(false);
        cbesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbescActionPerformed(evt);
            }
        });
        jPanel1.add(cbesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 165, 29));
        cbesc.getAccessibleContext().setAccessibleDescription("");

        cbmod.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbmod.setForeground(new java.awt.Color(0, 0, 0));
        cbmod.setEnabled(false);
        cbmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmodActionPerformed(evt);
            }
        });
        jPanel1.add(cbmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 250, 29));
        cbmod.getAccessibleContext().setAccessibleDescription("");

        txtpos.setBackground(new java.awt.Color(204, 204, 204));
        txtpos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpos.setForeground(new java.awt.Color(0, 0, 0));
        txtpos.setBorder(null);
        txtpos.setEnabled(false);
        jPanel1.add(txtpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 180, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Golos Marcados");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, 28));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Golos Sofridos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 238, 250, 28));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Numero de Pontos");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 238, 173, 28));

        txtgoM.setBackground(new java.awt.Color(255, 255, 255));
        txtgoM.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtgoM.setForeground(new java.awt.Color(0, 0, 0));
        txtgoM.setEnabled(false);
        jPanel1.add(txtgoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 165, 29));

        txtgos.setBackground(new java.awt.Color(255, 255, 255));
        txtgos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtgos.setForeground(new java.awt.Color(0, 0, 0));
        txtgos.setEnabled(false);
        jPanel1.add(txtgos, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 272, 250, 29));

        txtnump.setBackground(new java.awt.Color(255, 255, 255));
        txtnump.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtnump.setForeground(new java.awt.Color(0, 0, 0));
        txtnump.setEnabled(false);
        jPanel1.add(txtnump, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 272, 173, 29));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cartoes Amarelos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 319, 235, 28));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cartoes Vermelhos");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 319, 243, 28));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Ano");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 319, 150, 28));

        txtcartaoA.setBackground(new java.awt.Color(255, 255, 255));
        txtcartaoA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcartaoA.setForeground(new java.awt.Color(0, 0, 0));
        txtcartaoA.setEnabled(false);
        txtcartaoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcartaoAActionPerformed(evt);
            }
        });
        jPanel1.add(txtcartaoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 353, 165, 29));

        txtcartaoV.setBackground(new java.awt.Color(255, 255, 255));
        txtcartaoV.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcartaoV.setForeground(new java.awt.Color(0, 0, 0));
        txtcartaoV.setEnabled(false);
        txtcartaoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcartaoVActionPerformed(evt);
            }
        });
        jPanel1.add(txtcartaoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 353, 250, 29));

        txtano.setBackground(new java.awt.Color(255, 255, 255));
        txtano.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtano.setForeground(new java.awt.Color(0, 0, 0));
        txtano.setEnabled(false);
        jPanel1.add(txtano, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 353, 173, 29));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 250, 1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 180, 1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 180, 1));

        novo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        novo.setForeground(new java.awt.Color(0, 0, 0));
        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        grava.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        grava.setForeground(new java.awt.Color(0, 0, 0));
        grava.setText("Gravar");
        grava.setEnabled(false);
        grava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravaActionPerformed(evt);
            }
        });

        cancela.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cancela.setForeground(new java.awt.Color(0, 0, 0));
        cancela.setText("Cancelar");
        cancela.setEnabled(false);
        cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grava, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancela, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(grava, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(cancela, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel13.setText("REGISTRO DA FICHA ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Table Tennis_48px.png"))); // NOI18N
        jLabel14.setText("Sport Gerentior");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcartaoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcartaoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcartaoAActionPerformed

    private void txtcartaoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcartaoVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcartaoVActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
      flag=1;
      txtcod.setEnabled(true);
      txtnome.setEnabled(true);
      txtnum.setEnabled(true);
      txtcartaoA.setEnabled(true);
      txtcartaoV.setEnabled(true);
      txtgoM.setEnabled(true);
      txtgos.setEnabled(true);
      txtnump.setEnabled(true);
      cbesc.setEnabled(true);
      cbmod.setEnabled(true);
     txtpos.setEnabled(true);
     txtano.setEnabled(true);
     grava.setEnabled(true);
     cancela.setEnabled(true);
     novo.setEnabled(false);
    }//GEN-LAST:event_novoActionPerformed

    private void cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaActionPerformed
     txtcod.setEnabled(false);
      txtnome.setEnabled(false);
      txtnum.setEnabled(false);
      txtcartaoA.setEnabled(false);
      txtcartaoV.setEnabled(false);
      txtgoM.setEnabled(false);
      txtgos.setEnabled(false);
      txtnump.setEnabled(false);
      cbesc.setEnabled(false);
      cbmod.setEnabled(false);
     txtpos.setEnabled(false);
     grava.setEnabled(false);
     cancela.setEnabled(false);
     novo.setEnabled(true);
     txtcod.setText("");
     txtnome.setText("");
     txtnum.setText("");
      txtcartaoA.setText("");
      txtcartaoV.setText("");
      txtgoM.setText("");
      txtgos.setText("");
      txtnump.setText("");
       txtpos.setText("");
    }//GEN-LAST:event_cancelaActionPerformed

    private void cbescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbescActionPerformed
       try {
            ResultSet rs = cf.escalaoBaynome(cbesc.getSelectedItem().toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_cbescActionPerformed

    private void cbmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmodActionPerformed
        try {
            ResultSet rs = cf.ModalidadeBaynome(cbmod.getSelectedItem().toString());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_cbmodActionPerformed

    private void gravaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravaActionPerformed
      if(txtcod.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o campo codigo");
          txtcod.requestFocus();
      }else
      if(txtnome.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o campo nome");
          txtnome.requestFocus();
      }else
          if(txtcartaoA.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o campo cartao amarelo");
          txtcartaoA.requestFocus();
      }else
          if(txtcartaoV.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o campo cartao vermelho");
          txtcartaoV.requestFocus();
      }else
          if(txtano.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o campo ano");
          txtano.requestFocus();
      }else
          if(txtgoM.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o campo golos Marcados");
          txtgoM.requestFocus();
      }else
          if(txtgos.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o campo golos sofridos");
          txtgos.requestFocus();
      }else
          if(txtnum.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o campo numero de jogos");
          txtnum.requestFocus();
      }else
          if(txtnump.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o campo numero de pontos");
          txtnump.requestFocus();
      }else
          if(txtpos.getText().isEmpty()){
          JOptionPane.showMessageDialog(null,"Preencha o campo posicao");
          txtpos.requestFocus();
      }else
           if(flag==1){
               fic.setCodigo(Integer.parseInt(txtcod.getText()));
               fic.setNome(txtnome.getText());
               fic.setNrjogos(Integer.parseInt(txtnum.getText()));
               fic.setEscalao(verifica((String)cbesc.getSelectedItem()));
               fic.setModalidade(verificas((String)cbmod.getSelectedItem()));
               fic.setPos(txtpos.getText());
               fic.setGolosM(Integer.parseInt(txtgoM.getText()));
               fic.setGolosS(Integer.parseInt(txtgos.getText()));
               fic.setNump(Integer.parseInt(txtnump.getText()));
               fic.setCartaoA(Integer.parseInt(txtcartaoA.getText()));
               fic.setCartaoV(Integer.parseInt(txtcartaoV.getText()));
               fic.setAno(Integer.parseInt(txtano.getText()));
               cf.gravar(fic);
               txtano.setText("");
               txtcartaoA.setText("");
               txtcartaoV.setText("");
               txtpos.setText("");
               txtgoM.setText("");
               txtgos.setText("");
               txtnome.setText("");
               txtnump.setText("");
               txtnum.setText("");
               txtcod.setText("");
                txtcod.setEnabled(false);
      txtnome.setEnabled(false);
      txtnum.setEnabled(false);
      txtcartaoA.setEnabled(false);
      txtcartaoV.setEnabled(false);
      txtgoM.setEnabled(false);
      txtgos.setEnabled(false);
      txtnump.setEnabled(false);
      cbesc.setEnabled(false);
      cbmod.setEnabled(false);
     txtpos.setEnabled(false);
     grava.setEnabled(false);
     cancela.setEnabled(false);
     novo.setEnabled(true);
           }else{
                fic.setCodigo(Integer.parseInt(txtcod.getText()));
               fic.setNome(txtnome.getText());
               fic.setNrjogos(Integer.parseInt(txtnum.getText()));
               fic.setEscalao(verifica((String)cbesc.getSelectedItem()));
               fic.setModalidade(verificas((String)cbmod.getSelectedItem()));
               fic.setPos(txtpos.getText());
               fic.setGolosM(Integer.parseInt(txtgoM.getText()));
               fic.setGolosS(Integer.parseInt(txtgos.getText()));
               fic.setNump(Integer.parseInt(txtnump.getText()));
               fic.setCartaoA(Integer.parseInt(txtcartaoA.getText()));
               fic.setCartaoV(Integer.parseInt(txtcartaoV.getText()));
               fic.setAno(Integer.parseInt(txtano.getText()));
               cf.editar(fic);
               txtano.setText("");
               txtcartaoA.setText("");
               txtcartaoV.setText("");
               txtpos.setText("");
               txtgoM.setText("");
               txtgos.setText("");
               txtnome.setText("");
               txtnump.setText("");
               txtnum.setText("");
               txtcod.setText("");
                txtcod.setEnabled(false);
      txtnome.setEnabled(false);
      txtnum.setEnabled(false);
      txtcartaoA.setEnabled(false);
      txtcartaoV.setEnabled(false);
      txtgoM.setEnabled(false);
      txtgos.setEnabled(false);
      txtnump.setEnabled(false);
      cbesc.setEnabled(false);
      cbmod.setEnabled(false);
     txtpos.setEnabled(false);
     grava.setEnabled(false);
     cancela.setEnabled(false);
     novo.setEnabled(true);
           }   
    }//GEN-LAST:event_gravaActionPerformed


    
      public void carregarEscalao(){
      try {
            ResultSet rs = cf.escalao();
           rs.beforeFirst();
          
           
            while (rs.next()) {
                //System.out.println(rs.getString("nome"));
                esca.setCodigo(rs.getInt("codigoE"));
                esca.setNome(rs.getString("nome"));
                try{
                    cbesc.addItem((String)(Object)(esca.getNome()));
                }catch(NullPointerException np){
                    
                }
                
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "erro no preenchimento do combo box");
            ex.printStackTrace();
              
        }   
    }
 public void carregarmodalidade(){
      try {
            ResultSet rs = cf.Modalidade();
           rs.beforeFirst();
          
           
            while (rs.next()) {
                //System.out.println(rs.getString("nome"));
                mods.setCodigo(rs.getInt("codigoM"));
                mods.setNome(rs.getString("nome"));
                try{
                    cbmod.addItem((String)(Object)(mods.getNome()));
                }catch(NullPointerException np){
                    
                }
                
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "erro no preenchimento do combo box");
            ex.printStackTrace();
              
        }   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancela;
    private javax.swing.JComboBox<String> cbesc;
    private javax.swing.JComboBox<String> cbmod;
    private javax.swing.JButton grava;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton novo;
    private javax.swing.JTextField txtano;
    private javax.swing.JTextField txtcartaoA;
    private javax.swing.JTextField txtcartaoV;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtgoM;
    private javax.swing.JTextField txtgos;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtnump;
    private javax.swing.JTextField txtpos;
    // End of variables declaration//GEN-END:variables
}
