/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modeloConection.ConexaoBD;

/**
 *
 * @author Tsandzana
 */
public class LogFinal extends javax.swing.JFrame {
ConexaoBD bd=new ConexaoBD();
    /**
     * Creates new form LogFinal
     */
    public LogFinal() {
        initComponents();
        setLocationRelativeTo(null);
        bd.Conexao();
    }

   class JPanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
           Graphics2D g2d=(Graphics2D) g;
           int width=getWidth();
           int Height=getHeight();
           
           Color color1=new Color(51,51,51);
           Color color2=new Color(187,187,187);
           GradientPaint gp=new GradientPaint(0,0,color1,180,Height,color2);
           g2d.setPaint(gp);
           g2d.fillRect(0,0, width, Height);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new JPanelGradient();
        jLabel1 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        btlog = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Usaurio :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 177, 266, 28));

        txtuser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtuser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 211, 362, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Password :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 292, 163, 25));

        txtsenha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtsenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 323, 360, 32));

        btlog.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btlog.setText("Login");
        btlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogActionPerformed(evt);
            }
        });
        jPanel3.add(btlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 170, 40));

        jCheckBox1.setText("Visualizar");
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Heart Monitor_48px.png"))); // NOI18N
        jLabel3.setText("SADIM");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 48));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Gender Neutral User_96px.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 96, 96));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Alterar");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 410, 150, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogActionPerformed
     if(txtuser.getText().isEmpty()){
         JOptionPane.showMessageDialog(null,"campo user vaziu");
         txtuser.requestFocus();
     }else
          if(txtsenha.getText().isEmpty()){
         JOptionPane.showMessageDialog(null,"campo password vaziu");
         txtsenha.requestFocus();
          }else
             bd.executeSql("select *from usuario where nome='"+txtuser.getText()+"'");
              try{
                    bd.executeSql("select *from usuario where nome='"+txtuser.getText()+"'");
             bd.rs.first();
          if(bd.rs.getString("senha").equalsIgnoreCase(txtsenha.getText())){
              FrmPrincipal pr=new FrmPrincipal();
              pr.setVisible(true);
              dispose();
      }else{
              JOptionPane.showMessageDialog(null,"Senha ou usuario invalido");
          }
              }catch(SQLException ex){
                  JOptionPane.showMessageDialog(null,ex.getMessage());
              }
    }//GEN-LAST:event_btlogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlog;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
